### ISSUE TITLE
Issue Please Help

### ISSUE THREAD

**Issue by tannermays** [idolize/myspanishlab-solver#1]
How do you use this extension? I've installed it, but I'm not sure how it works. I am unable to right click within MySpanishLab. Thanks!

**Comment by idolize** [comment]
Hi @tannermays I am no longer maintaining this code; I'm not even sure if it still works on current versions of MySpanishLab.

The way it used to work was it would inject a "Solve" button directly into the page (no need to right click), which you could click and it would load in all the correct answers and submit the page for you.
